version: "3.8"
services:
    app:
        build: .
        volumes:
            - .:/dmp
        ports:
            - 8000:8000
        image: app:dmp
        container_name: dmp_container
        command: python manage.py runserver 0.0.0.0:8000