# Generated by Django 3.2.6 on 2021-08-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
