# Generated by Django 3.2.6 on 2021-08-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0004_auto_20210817_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
