# Generated by Django 3.2.6 on 2021-08-19 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0012_rename_id_dataset_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='booker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booker', to='datasetmanager.user', to_field='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
