# Generated by Django 3.2.6 on 2021-08-19 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0013_auto_20210819_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='booker',
        ),
        migrations.AddField(
            model_name='dataset',
            name='booker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
