# Generated by Django 3.2.6 on 2021-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='file_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
