# Generated by Django 3.2.6 on 2021-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetmanager', '0003_auto_20210817_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
